name = "qahal-dev"
main = "src/index.ts"
compatibility_date = "2026-04-19"
workers_dev = true
preview_urls = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "qahal-db-test"
database_id = "f016df17-62b2-4a2d-9053-4db87b6fd5df"
migrations_dir = "migrations"

[vars]
# Comma-separated list, for example:
# CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"
CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"
APP_ENV = "development"
INVITE_GATE_ENABLED = "true"

[[routes]]
pattern = "api-development.qahal.xyz"
zone_name = "qahal.xyz"
custom_domain = true

[env.production.vars]
APP_ENV = "production"
INVITE_GATE_ENABLED = "true"
CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"

[env.production]
name = "qahal"
workers_dev = true
preview_urls = true

[[env.production.routes]]
pattern = "api.qahal.xyz"
zone_name = "qahal.xyz"
custom_domain = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "qahal-db-prod"
database_id = "1656b753-16ac-4658-ad51-addc7c9b59f8"
migrations_dir = "migrations"
